#[cfg(feature = "lol")]
pub mod account_v1;
#[cfg(feature = "lol")]
pub mod champion_mastery_v4;
#[cfg(feature = "lol")]
pub mod champion_v3;
#[cfg(feature = "lol")]
pub mod league_exp_v4;
#[cfg(feature = "lol")]
pub mod league_v4;
#[cfg(feature = "lol")]
pub mod lol_challenges_v1;
#[cfg(feature = "lol")]
pub mod lol_status_v4;
#[cfg(feature = "lol")]
pub mod match_v5;

#[cfg(feature = "clash")]
pub mod clash_v1;
