[package]
name = "riot-api"
version = "0.1.0"
edition = "2021"

[dependencies]
log = "0.4.20"
chrono = "0.4.31"

[dependencies.serde]
version = "1.0.193"
features = ["derive"]

[dependencies.reqwest]
version = "0.11.22"
features = ["json", "serde_json"]

[dev-dependencies]
reqwest = "0.11.22"
dotenv = "0.15.0"
pretty_env_logger = "0.5.0"

[dev-dependencies.tokio]
version = "1.34.0"
features = ["full"]

[features]
default = ["lol"]
lol = []
clash = []
tft = []
val = []